### ISSUE TITLE
Typo in the About section of the repository

### ISSUE THREAD

**Issue by theoden9014** [metarank/metarank#1037]
Hello,

I noticed a minor typo in the About section of the repository. The current description reads:

"A low code Machine Learning peersonalized ranking service for articles, listings, search results, recommendations that boosts user engagement. A friendly Learn-to-Rank engine"

I believe "peersonalized" should be "personalized". 

Suggested correction:

"A low code Machine Learning personalized ranking service for articles, listings, search results, recommendations that boosts user engagement. A friendly Learn-to-Rank engine"

Thank you for your attention to this matter.

**Comment by vgoloviznin** [comment]
Thanks for finding this out!
