### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by meg261995** [metarank/metarank#1061]
Hi,

So I am just getting started with Meta rank for personalization of search. Currently I am using ES_LTR for scoring documents and now I want to integrate MetaRank for personlization. In the readme I clicked on Personalization: [secondary reranking] which led me to the link (https://github.com/metarank/metarank/blob/master/quickstart/quickstart.md) which throws an error PAGE NOT FOUND. Can anybody help me out on how to get started?

**Comment by vgoloviznin** [comment]
Hey @meg261995 , can you check out the official doc site: https://docs.metarank.ai/introduction/quickstart? Looks like there's something weird with linking in github

**Comment by meg261995** [comment]
Yep ended up there only. Thanks!
