### ISSUE TITLE
Support for multilingual LLMs

### ISSUE THREAD

**Issue by AndreasKleineberg** [metarank/metarank#1110]
Currently, the Huggingface repository of metarank contains only English embedding models. However, there are also multilingual models from Sentence Transformers, e.g. [distiluse-base-multilingual-cased-v1](https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v1). At least one multilingual embedding model would be helpful as an integration in metarank.

**Comment by shuttie** [comment]
@AndreasKleineberg I've did an ONNX translation of the E5-multilingual-small model: https://huggingface.co/metarank/multilingual-e5-small - seems to be working OK. If you encounter any issues working with this model, feel free to re-open the issue.
