### ISSUE TITLE
Getting secondary ranking with Metarank

### ISSUE THREAD

**Issue by meg261995** [metarank/metarank#1126]
Hi All,

I'm trying to get clarity on the post-training re-ranking process of Meta Rank. I'm currently following [this](https://docs.metarank.ai/introduction/intro) demo where, after the algorithm is trained, it involves a sequence of three steps to achieve personalized rankings. First, there's the ranking step to send impression data, followed by interaction to gather user feedback, and finally another ranking event to obtain the personalized ranking. I'm curious about how this can be implemented in real-time scenarios where we typically aim for immediate personalization? The initial ranking is performed by the internal retrieval system, and then this data is sent to Meta Rank for secondary re-ranking, omitting the step of sending real time impression data as shown in the demonstration. Please do not mind me being naive here as I am just getting started with this. Can anyone please explain this? Thanks in advance.

**Comment by vgoloviznin** [comment]
Hello @meg261995, sorry for the delay in replying here. 

Unfortunately, if you will not send impression data, then personalization will not behave as expected. Impression information is used in the model to understand what items are relevant to a specific user, which powers personalization. You can check out this blog post to deeper understand how personalization works: https://blog.metarank.ai/personalized-search-with-metarank-and-elasticsearch-a5a098548da7

**Comment by meg261995** [comment]
Hey,

I will be sending impression data, which is all the products shown to the user.  In the demo along with impression data, real time interaction is also fed.. This is a multi step process. My question was whether this was needed or not. Impression data is definitely needed, no doubt here

**Comment by vgoloviznin** [comment]
The clickstream is also needed as it separates relevant items from irrelevant ones for the user and it's connected to the impression data sent before the click. You can't omit this data as well as the model will not behave as expected. Although you can batch upload impressions and clickthroughs later, you will not get the real-time personalization. 

However, if you don't need personalization per se, you can create a model that does not depend on click events, in this case 'personalization' will be generic for all users making requests, but you won't need to send impressions and clicks in real time and can just re-train the model when needed.

**Comment by vgoloviznin** [comment]
Closing too old issue
