### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by puzzle29** [metarank/metarank#332]
Hello !
On the [demo](https://demo.metarank.ai/) page when I click on a movie, nothing show up and I got a 504 status code in the console.

I don't know if it's normal. I'm using the latest version of Chrome.

**Comment by vgoloviznin** [comment]
Hey @puzzle29, it's a known issue due to the load we get on the demo. At the moment we're resurrecting it manually, but the fix is on it's way next week.

Sorry for the troubles!

**Comment by puzzle29** [comment]
Okay I see,
Thanks
