### ISSUE TITLE
Config file validation is broken

### ISSUE THREAD

**Issue by vgoloviznin** [metarank/metarank#481]
Running 
```java -jar metarank.jar validate --config config.yml ```

Returns 

```
15:49:42.958 INFO  a.m.mode.validate.ConfigValidator$ - config file is a YAML object
ai.metarank.mode.validate.Validate$ValidationError: 'interactions' section is missing in config
        at ai.metarank.mode.validate.Validate$.checkConfig(Validate.scala:35)
        at ai.metarank.mode.validate.Validate$.run(Validate.scala:13)
        at ai.metarank.Main$.run(Main.scala:21)
        at map @ ai.metarank.mode.validate.Validate$.run(Validate.scala:12)
```

Looks like a regression after config file format change

**Comment by shuttie** [comment]
So technically speaking the validation is conceptually broken, so thats why we're not rushing to fix it right now. The plan is to make it more resilient:
1. Compute a ton of statistics over the input dataset: which event types, which fields, field types and value distributions.
2. Compare the actual config file with the dataset stat model
3. Alert on suspicious things.

The same dataset stat can be used in another direction, to generate a typical baseline feature extractor setup, so user don't need to struggle with reading docs :)

**Comment by shuttie** [comment]
Fixed
