### ISSUE TITLE
Github link on the documentation has a typo

### ISSUE THREAD

**Issue by kamaravichow** [metarank/metarank#654]
I don't know if it's worth anything but, I observed that clicking on the GitHub option on the header of documentation page redirects you to. "Github 404"

I think you made a typo in the link:

Current Behaviour:
"https://github.com/metarank/metarankk"

Expected Behaviour:
"https://github.com/metarank/metarank"

**Comment by shuttie** [comment]
Thanks for a hint, fixed:
![image](https://user-images.githubusercontent.com/999061/191298974-befd9689-66ce-453e-90c9-c25079043ee8.png)
