### ISSUE TITLE
Error unable to find image/Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /lib/linux/aarch64/libxgboost4j.so was not found inside JAR. 	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:37) 	... 10 more

### ISSUE THREAD

**Issue by Aquib4tringam** [metarank/metarank#743]
Hey Team,
I am trying to run the commands on my MacBook M1 chip, the exact curl commands given on the page. However, always end up with errors . 
<img width="567" alt="Screenshot 2022-11-16 at 11 00 46 AM" src="https://user-images.githubusercontent.com/118331290/202091948-2b10e026-e51b-4ad1-85bf-5abe33701d6e.png">
<img width="1128" alt="Screenshot 2022-11-16 at 11 02 03 AM" src="https://user-images.githubusercontent.com/118331290/202092121-10299200-ef92-43b3-8937-63ca563b68f7.png">
I am attaching the error screenshots below please check. it cannot start the docker image.

**Comment by shuttie** [comment]
But the exception is still valid, there is no linux/aarch64 native library for both lightgbm & xgboost
