### ISSUE TITLE
HI，could we support  keras  and pytorch  or  javacpp scala pytorch tensorflow-java?

### ISSUE THREAD

**Issue by mullerhai** [metarank/metarank#768]
HI, 
        metarank is best ctr tools for  online ,I think we need to support more type framework model ,like pytorch and keras

thanks

**Comment by shuttie** [comment]
Can you please describe the use-case for PyTorch? 

We do have plans regarding Python in general for a foreseeable future:
- API bindings for Python (#641 )
- Wrap sasrec/bert4rec into metarank for more complete support of recommendations retrieval.

But metarank is a service, and not a library - how should we integrate it with PyTorch? we’re always glad to hear about use cases we never thought about :)

**Comment by mullerhai** [comment]
> Can you please describe the use-case for PyTorch?
> 
> We do have plans regarding Python in general for a foreseeable future:
> 
> * API bindings for Python ([Python metarank API client #641](https://github.com/metarank/metarank/issues/641) )
> * Wrap sasrec/bert4rec into metarank for more complete support of recommendations retrieval.
> 
> But metarank is a service, and not a library - how should we integrate it with PyTorch? we’re always glad to hear about use cases we never thought about :)

I think  metarank could be Recommend System framework for us business, Now our recommend system not use xgboost  lightbgm as backend ,because of them are old and optimic is not easy  for the acc auc,we  just use pytorch  tensorflow, ,I has see our metarank source code ,we use xgb  lightbgm invoke, so  we just add the pytorch-javacpp  tensorflow-java  implement is ok

**Comment by vgoloviznin** [comment]
We're considering adding support for different recommendations algorithms out of the box in the future releases, so that you can generate recommendations and then personalize them with Metarank without using third-party systems.

**Comment by mullerhai** [comment]
> We're considering adding support for different recommendations algorithms out of the box in the future releases, so that you can generate recommendations and then personalize them with Metarank without using third-party systems.

please support deep learning algorithm  neural network  future  and  can use define the algorithm ， like  deepfm  acn  xdeepfm  ffm  and so on. thanks ,But I think if you solve how to use the pytorch or keras become your framework algorithm bakcend ,everything  could be solved

**Comment by vgoloviznin** [comment]
Closing as an old issue
