### ISSUE TITLE
Multiple ranking types/contexts

### ISSUE THREAD

**Issue by tomtaylor** [metarank/metarank#780]
Hello, I'm kicking the tyres on Metarank. Does it support multiple ranking types for different contexts? For example: the ideal ranking outcome is likely different for search results vs home page vs sidebars. Is it possible to indicate what the context is in the ranking event, and use request rerankings for that context?

**Comment by vgoloviznin** [comment]
Hey @tomtaylor this is something that's missing now, as the only way for now is to have separate instances of Metarank. @romangrebennikov will make a longer answer :)

**Comment by vgoloviznin** [comment]
@tomtaylor support for selecting the model for which you're sending ranking events will be coming in the future release :)

**Comment by shuttie** [comment]
Yep, it will be a part of the next release. ETA - end of this week.

**Comment by tomtaylor** [comment]
Amazing, thanks folks!
