### ISSUE TITLE
Incorporating explicit preferences into Metarank?

### ISSUE THREAD

**Issue by tomtaylor** [metarank/metarank#804]
We're interested in incorporating explicit preferences with implicit click behaviour into Metarank, but I'm not sure of the best way to model this or if this is even possible right now.

For example, we might ask a user if they're interested in category A, B and C when they sign up, and then use that information to drive their initial recommendations from within those categories. But then, also incorporate their click behaviour over time.

I was considering making category A, B, and C into special items, presented as individual ranking events, followed by subsequent positive or negative interaction events. The positive events would have a weight of 1.0 and the negative events would have a weight of -1.0. That would bootstrap the user's preferences, before moving to implicit feedback loops.

Does this seem like a feasible approach or is there another way to approach this problem?

**Comment by vgoloviznin** [comment]
Hey Tom, 

One of the things you can do at the moment is sending user preferences as user metadata and then adding a feature based on that metadata. You can send user metadata in the same way as item metadata. 

May be @romangrebennikov has some ideas as well

**Comment by tomtaylor** [comment]
@vgoloviznin thanks - that make sense. It looks like features are usually scoped to either a user or an item - how would you indicate that a feature is shared by both?

**Comment by vgoloviznin** [comment]
Yes, at the moment it's not possible to use one feature with multiple scopes, so it will be 2 different features - one for an item, one for a user. 

It's hard to say if you will be able achieve the result you want, you will need to run some tests. 

Also the proposal you had in the original post might work, but we've never tries such a setup. 

Roman will give a more thorough answer and some suggestions a bit later :)
